name: Run Pylint

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  actions: write

jobs:
  run-pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        uses: ./.github/actions/setup-python-deps

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
